version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Entered the install phase...
      - echo About to build $RESOURCE_PATH
      - export PATH="/usr/local/bin:$PATH"
      - /usr/local/bin/dockerd-entrypoint.sh
      - cat /var/log/docker.log
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - echo "Loading nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && nvm install 16 && nvm install-latest-npm
      - npm --version
      - node --version
      - pwd
      - ls
  build:
    commands:
      - pip uninstall aws-sam-cli -y
      - cfn --version
      - pip show cloudformation-cli-typescript-plugin
      - pip show cloudformation-cli
      - pip install cloudformation-cli -U
      - pip install cloudformation-cli-typescript-plugin -U
      - pip show cloudformation-cli-typescript-plugin
      - pip show cloudformation-cli
      - echo Entered the build phase...
      - npm install && npm run build
      - cd $RESOURCE_PATH
      - pwd
      - ls
      - npm install && npm run build
      - ./setup.sh
      - echo Debug SAM build...
      - sam --version
      - which sam
      - ls -l /usr/local/bin/sam
      - sudo rm -rf /usr/local/bin/sam
      - sudo rm -rf /usr/local/aws-sam-cli
      - curl https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -O -L
      - unzip -q -o aws-sam-cli-linux-x86_64.zip -d sam-installation
      - sudo ./sam-installation/install
      - sam --version
      - which sam
      - export TYPE_NAME=$(cat .rpdk-config | jq -r .typeName)
      - printenv TYPE_NAME
      - ../publish-resource-regions.sh
    finally:
      - cat rpdk.log
      - ./cleanup.sh    
