---
AWSTemplateFormatVersion: '2010-09-09'

Description: |
  The following CloudFormation Dynatrace resource types allow the creation and configuration of 
  service level objectives, locations, monitors and metrics related to your application.
  This allows kicking off monitoring of new projects simply, efficiently, and consistently.

Parameters:
  NodeIds:
    Type: List<Number>
    Description: Enter the IDs of existing nodes, capable of running monitors

Resources:
  # 1. Custom metrics
  TimeToCompletionMetric:
    Type: Dynatrace::Environment::Metric
    Properties:
      TimeseriesId: custom:kpis.timeToCompletion
      DisplayName: Average time for a customer to complete the sales process, from cart
      Unit: Second (s)
      Dimensions:
        - ACME
        - KPIS
      Types:
        - Web
  SuccessCountMetric:
    Type: Dynatrace::Environment::Metric
    Properties:
      TimeseriesId: custom:kpis.successCount
      DisplayName: Number of people having something in their cart and completing the sale
      Unit: Count (count)
      Dimensions:
        - ACME
        - KPIS
      Types:
        - Web
  DropCountMetric:
    Type: Dynatrace::Environment::Metric
    Properties:
      TimeseriesId: custom:kpis.dropCount
      DisplayName: Number of people having something in their cart, to failing to complete the sale
      Unit: Count (count)
      Dimensions:
        - ACME
        - KPIS
      Types:
        - Web

  # 2. Location and monitor
  ActiveGateLocation:
    Type: Dynatrace::Environment::SyntheticLocation
    Properties:
      Type: PRIVATE
      Name: UK ActiveGate
      CountryCode: GB
      City: Edinburgh
      Latitude: 55.9533
      Longitude: 3.1883
      LocationNodeOutageDelayInMinutes: 3
      Nodes: !Ref NodeIds
  HealthMonitor:
    Type: Dynatrace::Environment::SyntheticMonitor
    Properties:
      FrequencyMin: 5
      Name: ACME Health Monitor
      Enabled: true
      Type: HTTP
      AnomalyDetection:
        OutageHandling:
          GlobalOutage: true
          GlobalOutagePolicy:
            ConsecutiveRuns: 3
          LocalOutage: true
          LocalOutagePolicy:
            AffectedLocations: 1
            ConsecutiveRuns: 3
        LoadingTimeThresholds:
          Enabled: true
          Thresholds:
            - Type: TOTAL
              ValueMs: 100
      Script:
        Version: 1.0
        Requests:
          - Url: https://aws.amazon.com
            Method: GET
            Description: HTTP request test
            Validation:
              Rules:
                - Type: httpStatusesList
                  Value: 500, 400
                  PassIfFound: false
                - Type: httpStatusesList
                  Value: 200, 204, 302
                  PassIfFound: true
      Locations:
        - !Ref ActiveGateLocation

  # 3. Service level objective
  SaleFailureServiceLevelObjective:
    Type: Dynatrace::Environment::ServiceLevelObjective
    DependsOn:
      - SuccessCountMetric
      - DropCountMetric
    Properties:
      Name: Sale failure
      MetricExpression: "(100)*(ext:kpis.dropCount)/(ext:kpis.successCount)"
      EvaluationType: AGGREGATE
      Target: 1
      Warning: 3
      ErrorBudgetBurnRate:
        FastBurnThreshold: 10
        BurnRateVisualizationEnabled: true
      Timeframe: "-1w"

  # 4. Dashboard
  AcmeDashboard:
    Type: Dynatrace::Configuration::Dashboard
    Properties:
      DashboardMetadata:
        Name: Acme Dashboard
        Owner: CloudFormation
        Shared: false
        Tags:
          - CloudFormation
          - Dynatrace
      Tiles:
        - Name: Sales failure
          TileType: SLO
          Configured: true
          Bounds:
            Top: 0
            Left: 0
            Width: 304
            Height: 152
          TileFilter:
            Timeframe: -1w
          AssignedEntities:
            - !Ref SaleFailureServiceLevelObjective
          Metric: METRICS=true;LEGEND=true;PROBLEMS=true;decimals=10;customTitle=Overall sale failure;
        - Name: Uptime
          TileType: SYNTHETIC_HTTP_MONITOR
          Configured: true
          Bounds:
            Top: 0
            Left: 304
            Width: 304
            Height: 304
          AssignedEntities:
            - !Ref HealthMonitor
        - Name: Completion time
          TileType: DATA_EXPLORER
          Configured: true
          Bounds:
            Top: 152
            Left: 0
            Width: 304
            Height: 304
          CustomName: Data explorer results
          Queries:
            - Id: A
              Metric: ext:kpis.timeToCompletion
              TimeAggregation: DEFAULT
              SortBy: DESC
              Limit: 100
              Enabled: true
          VisualConfig:
            Type: GRAPH_CHART
            Global:
              HideLegend: false
            Rules:
              - Matcher: "A:"
                Properties:
                  Color: DEFAULT
            Axes:
              xAxis:
                displayName: ""
                visible: true
              yAxes:
                - displayName: ""
                  visible: true
                  min: AUTO
                  max: AUTO
                  position: LEFT
                  queryIds:
                    - A
                  defaultAxis: true
            heatmapSettings:
              yAxis: VALUE
            thresholds:
              - axisTarget: LEFT
                rules:
                  - color: "#7dc540"
                  - color: "#f5d30f"
                  - color: "#dc172a"
                queryId: ""
                visible: true
            tableSettings:
              isThresholdBackgroundAppliedToCell: false
            graphChartSettings:
              connectNulls: false
            honeycombSettings:
              showHive: true
              showLegend: true
              showLabels: false